version: "3.9"

services:
  db:
    image: postgres
    volumes:
      # TODO: find out why use that
      # - app-db-data:/var/lib/postgresql/data/pgdata
      - ${DOCKER_PROJECT_PATH:-.}/data/pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=maindb
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    # deploy:
    #   placement:
    #     constraints:
    #       - node.labels.${STACK_NAME?Variable not set}.app-db-data == true

  bot:
    build: ./bot
    environment:
      - BOT_API_TOKEN
    volumes:
      - ${DOCKER_PROJECT_PATH:-.}/bot:/app
    command: sh -c 'wait-for -t 15 db:5432 -- python db/init_db.py && python main.py'

  backend:
    build: ./backend
    volumes:
      #TODO: duplicate
      - ${DOCKER_PROJECT_PATH:-.}/backend:/app
    command: sh -c 'wait-for db:5432 -- strawberry export-schema schema:schema'

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
  #       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
  #   ports:
  #       - "5050:80"
  #   volumes:
  #       # Don't forget to set owner:group for this dir as 5050:5050
  #       # (sudo chown -R 5050:5050 <this path>)
  #       - ${DOCKER_PROJECT_PATH:-.}/data/pgadmin:/var/lib/pgadmin

# volumes:
#   app-db-data:
