# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
# Triggers the workflow on push or pull request events but only for the "master" branch
on:
  push:
    branches: [ "master" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/b21-02-anonymous-feedback
            git switch master && git pull
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} > .env
            echo BOT_API_TOKEN=${{ secrets.BOT_API_TOKEN }} >> .env
            echo SECRET_KEY=${{ secrets.COOKIE_SECRET_KEY }} >> .env
            docker compose down
            docker compose up -d --build



      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
